name: Build and deploy

# Can be triggered by push and by manual interaction
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm build
        
      - name: Create and upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-artifact
          path: dist/www
          retention-days: 1
          overwrite: true

  # - In a separate job, deploy the content of that archive to GitHub Pages
